### ISSUE TITLE
Test `fixtures/url_unicode_hostname/app.py` failing

### ISSUE THREAD

**Issue by nappex** [encukou/freezeyt#369]
Problem should be on python version > 3.7

Pytest output:

```shell
------------------------------ Captured log call -------------------------------
ERROR    app:app.py:1741 Exception on / [GET]
Traceback (most recent call last):
  File "freezeyt/__venv310__/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "freezeyt/__venv310__/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "freezeyt/__venv310__/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "freezeyt/__venv310__/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "freezeyt/tests/fixtures/url_unicode_hostname/app.py", line 19, in index
    assert sys.version_info < (3, 8)
AssertionError
=========================== short test summary info ============================
FAILED tests/test_expected_output.py::test_output[url_unicode_hostname] - fre...
=================== 1 failed, 559 passed, 1 skipped in 7.41s ===================
```

**Comment by encukou** [comment]
Update your Flask :)
